"""add first_viewed_at to post_stats

Revision ID: 5ef838f3c962
Revises: e11dd0161079
Create Date: 2026-02-24 16:33:26.616812

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ef838f3c962'
down_revision: Union[str, Sequence[str], None] = 'e11dd0161079'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post_stats', sa.Column('first_viewed_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post_stats', 'first_viewed_at')
    # ### end Alembic commands ###
